version: "3.8"

services:
  backend:
    build: ./todo-backend
    ports:
      - "33333:33333"
    command: bun run index.ts

  frontend:
    build: ./todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
